package xiuxian.sect;

import java.util.LinkedHashMap;
import java.util.Map;

import net.minecraft.core.BlockPos;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.saveddata.SavedData;

/**
 * Durable state for the generated Luoxia inner realm.
 *
 * <p>The realm is generated by {@link LuoxiaInnerRealmGenerator} as one
 * deterministic pass.  Keeping this state in the dimension's own
 * DataStorage means re-opening the world, or loading a different dimension,
 * cannot shuffle the unique residences or cave route.</p>
 */
final class LuoxiaInnerRealmData extends SavedData {
    static final String DATA_ID = "xiuxian_luoxia_inner_realm";

    int version;
    long seed;
    boolean generated;
    final Map<String, BlockPos> markers = new LinkedHashMap<>();

    static LuoxiaInnerRealmData get(ServerLevel level) {
        return level.getDataStorage().computeIfAbsent(LuoxiaInnerRealmData::load,
                LuoxiaInnerRealmData::new, DATA_ID);
    }

    static LuoxiaInnerRealmData load(CompoundTag tag) {
        LuoxiaInnerRealmData data = new LuoxiaInnerRealmData();
        data.version = tag.getInt("Version");
        data.seed = tag.getLong("Seed");
        data.generated = tag.getBoolean("Generated");
        CompoundTag markerTag = tag.getCompound("Markers");
        for (String key : markerTag.getAllKeys()) {
            if (markerTag.contains(key)) data.markers.put(key, BlockPos.of(markerTag.getLong(key)));
        }
        return data;
    }

    @Override
    public CompoundTag save(CompoundTag tag) {
        tag.putInt("Version", version);
        tag.putLong("Seed", seed);
        tag.putBoolean("Generated", generated);
        CompoundTag markerTag = new CompoundTag();
        for (Map.Entry<String, BlockPos> marker : markers.entrySet()) {
            markerTag.putLong(marker.getKey(), marker.getValue().asLong());
        }
        tag.put("Markers", markerTag);
        return tag;
    }

    void marker(String id, BlockPos pos) {
        markers.put(id, pos.immutable());
    }
}
