package xiuxian.block;

import java.util.LinkedHashMap;
import java.util.Map;
import net.minecraft.world.item.*;
import net.minecraft.world.item.crafting.RecipeType;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraftforge.event.BuildCreativeModeTabContentsEvent;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.*;
import xiuxian.vein.*;

/** Generated by tools/vein_assets.py; interaction implementations are maintained separately. */
public final class VeinBlocks {
    public enum Kind { ROCK, ORE, CLUSTER, CUBE, BRACE, RAIL, SLAB, CHAIN, GRATE, PILLAR, CRAFT, CAGE, SWITCH, LAMP, CACHE, GATE, SENSOR, STATION, SEAT }
    private static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, "xiuxian");
    private static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, "xiuxian");
    private static final DeferredRegister<BlockEntityType<?>> ENTITIES = DeferredRegister.create(ForgeRegistries.BLOCK_ENTITY_TYPES, "xiuxian");
    private static final Map<String, RegistryObject<Block>> RESOURCES = new LinkedHashMap<>();
    private static final Map<String, RegistryObject<Item>> MATERIALS = new LinkedHashMap<>();
    static {
        add("vein_dew_rock", Kind.ROCK, 1, new double[][]{{0,0,0,16,16,16}});
        add("vein_dew_ore", Kind.ORE, 1, new double[][]{{0,0,0,16,16,16}});
        add("vein_dew_cluster", Kind.CLUSTER, 1, new double[][]{{2,0,2,14,2,14},{6,2,6,10,16,10},{2,2,3,5,13,6},{11,2,9,14,11,12}});
        add("vein_dew_block", Kind.CUBE, 1, new double[][]{{0,0,0,16,16,16}});
        add("vein_frost_rock", Kind.ROCK, 2, new double[][]{{0,0,0,16,16,16}});
        add("vein_frost_ore", Kind.ORE, 2, new double[][]{{0,0,0,16,16,16}});
        add("vein_frost_cluster", Kind.CLUSTER, 2, new double[][]{{2,0,2,14,2,14},{6,2,6,10,16,10},{2,2,3,5,13,6},{11,2,9,14,11,12}});
        add("vein_frost_block", Kind.CUBE, 2, new double[][]{{0,0,0,16,16,16}});
        add("vein_azure_rock", Kind.ROCK, 3, new double[][]{{0,0,0,16,16,16}});
        add("vein_azure_ore", Kind.ORE, 3, new double[][]{{0,0,0,16,16,16}});
        add("vein_azure_cluster", Kind.CLUSTER, 3, new double[][]{{2,0,2,14,2,14},{6,2,6,10,16,10},{2,2,3,5,13,6},{11,2,9,14,11,12}});
        add("vein_azure_block", Kind.CUBE, 3, new double[][]{{0,0,0,16,16,16}});
        add("vein_jade_rock", Kind.ROCK, 4, new double[][]{{0,0,0,16,16,16}});
        add("vein_jade_ore", Kind.ORE, 4, new double[][]{{0,0,0,16,16,16}});
        add("vein_jade_cluster", Kind.CLUSTER, 4, new double[][]{{2,0,2,14,2,14},{6,2,6,10,16,10},{2,2,3,5,13,6},{11,2,9,14,11,12}});
        add("vein_jade_block", Kind.CUBE, 4, new double[][]{{0,0,0,16,16,16}});
        add("vein_ember_rock", Kind.ROCK, 5, new double[][]{{0,0,0,16,16,16}});
        add("vein_ember_ore", Kind.ORE, 5, new double[][]{{0,0,0,16,16,16}});
        add("vein_ember_cluster", Kind.CLUSTER, 5, new double[][]{{2,0,2,14,2,14},{6,2,6,10,16,10},{2,2,3,5,13,6},{11,2,9,14,11,12}});
        add("vein_ember_block", Kind.CUBE, 5, new double[][]{{0,0,0,16,16,16}});
        add("vein_cinnabar_rock", Kind.ROCK, 6, new double[][]{{0,0,0,16,16,16}});
        add("vein_cinnabar_ore", Kind.ORE, 6, new double[][]{{0,0,0,16,16,16}});
        add("vein_cinnabar_cluster", Kind.CLUSTER, 6, new double[][]{{2,0,2,14,2,14},{6,2,6,10,16,10},{2,2,3,5,13,6},{11,2,9,14,11,12}});
        add("vein_cinnabar_block", Kind.CUBE, 6, new double[][]{{0,0,0,16,16,16}});
        add("vein_gold_rock", Kind.ROCK, 7, new double[][]{{0,0,0,16,16,16}});
        add("vein_gold_ore", Kind.ORE, 7, new double[][]{{0,0,0,16,16,16}});
        add("vein_gold_cluster", Kind.CLUSTER, 7, new double[][]{{2,0,2,14,2,14},{6,2,6,10,16,10},{2,2,3,5,13,6},{11,2,9,14,11,12}});
        add("vein_gold_block", Kind.CUBE, 7, new double[][]{{0,0,0,16,16,16}});
        add("vein_violet_rock", Kind.ROCK, 8, new double[][]{{0,0,0,16,16,16}});
        add("vein_violet_ore", Kind.ORE, 8, new double[][]{{0,0,0,16,16,16}});
        add("vein_violet_cluster", Kind.CLUSTER, 8, new double[][]{{2,0,2,14,2,14},{6,2,6,10,16,10},{2,2,3,5,13,6},{11,2,9,14,11,12}});
        add("vein_violet_block", Kind.CUBE, 8, new double[][]{{0,0,0,16,16,16}});
        add("vein_origin_rock", Kind.ROCK, 9, new double[][]{{0,0,0,16,16,16}});
        add("vein_origin_ore", Kind.ORE, 9, new double[][]{{0,0,0,16,16,16}});
        add("vein_origin_cluster", Kind.CLUSTER, 9, new double[][]{{2,0,2,14,2,14},{6,2,6,10,16,10},{2,2,3,5,13,6},{11,2,9,14,11,12}});
        add("vein_origin_block", Kind.CUBE, 9, new double[][]{{0,0,0,16,16,16}});
        add("vein_strata_slate", Kind.ROCK, 0, new double[][]{{0,0,0,16,16,16}});
        add("vein_porous_limestone", Kind.ROCK, 0, new double[][]{{0,0,0,16,16,16}});
        add("vein_mica_schist", Kind.ROCK, 0, new double[][]{{0,0,0,16,16,16}});
        add("vein_magnetite", Kind.ROCK, 0, new double[][]{{0,0,0,16,16,16}});
        add("vein_sulfur_rock", Kind.ROCK, 0, new double[][]{{0,0,0,16,16,16}});
        add("vein_salt_rock", Kind.ROCK, 0, new double[][]{{0,0,0,16,16,16}});
        add("vein_red_ironstone", Kind.ROCK, 0, new double[][]{{0,0,0,16,16,16}});
        add("vein_obsidian_breccia", Kind.ROCK, 0, new double[][]{{0,0,0,16,16,16}});
        add("vein_calcite_ribs", Kind.ROCK, 0, new double[][]{{0,0,0,16,16,16}});
        add("vein_fossil_shale", Kind.ROCK, 0, new double[][]{{0,0,0,16,16,16}});
        add("vein_aquifer_rock", Kind.ROCK, 0, new double[][]{{0,0,0,16,16,16}});
        add("vein_rootstone", Kind.ROCK, 0, new double[][]{{0,0,0,16,16,16}});
        add("vein_reinforced_floor", Kind.CUBE, 0, new double[][]{{0,0,0,16,16,16}});
        add("vein_survey_tile", Kind.CUBE, 0, new double[][]{{0,0,0,16,16,16}});
        add("vein_support_brace", Kind.BRACE, 0, new double[][]{{0,0,0,3,16,3},{13,0,0,16,16,3},{0,13,0,16,16,5}});
        add("vein_safety_rail", Kind.RAIL, 0, new double[][]{{0,0,6,2,16,10},{14,0,6,16,16,10},{2,10,7,14,13,9},{2,3,7,14,6,9}});
        add("vein_bridge_slab", Kind.SLAB, 0, new double[][]{{0,0,0,16,16,16}});
        add("vein_anchor_chain", Kind.CHAIN, 0, new double[][]{{6,0,7,10,16,9},{7,1,5,9,6,11},{7,10,5,9,15,11}});
        add("vein_drain_grate", Kind.GRATE, 0, new double[][]{{0,0,0,16,2,2},{0,0,14,16,2,16},{0,0,2,2,2,14},{4,0,2,6,2,14},{8,0,2,10,2,14},{12,0,2,14,2,14}});
        add("vein_pressure_pillar", Kind.PILLAR, 0, new double[][]{{1,0,1,15,2,15},{4,2,4,12,14,12},{1,14,1,15,16,15}});
        add("vein_survey_bench", Kind.CRAFT, 0, new double[][]{{0,0,0,16,16,16}});
        add("vein_arena_basalt", Kind.ROCK, 0, new double[][]{{0,0,0,16,16,16}});
        add("vein_arena_floor", Kind.CUBE, 0, new double[][]{{0,0,0,16,16,16}});
        add("vein_fracture_tile", Kind.CUBE, 0, new double[][]{{0,0,0,16,16,16}});
        add("vein_shield_pillar", Kind.PILLAR, 0, new double[][]{{1,0,1,15,2,15},{4,2,4,12,14,12},{1,14,1,15,16,15}});
        add("vein_seal_cage", Kind.CAGE, 0, new double[][]{{1,0,1,15,2,15},{1,14,1,15,16,15},{1,2,1,3,14,3},{1,2,13,3,14,15},{13,2,1,15,14,3},{13,2,13,15,14,15}});
        add("vein_resonance_pedestal", Kind.SWITCH, 0, new double[][]{{1,0,1,15,3,15},{4,3,4,12,7,12},{6,7,6,10,11,10}});
        add("vein_pulse_beacon", Kind.LAMP, 0, new double[][]{{3,0,3,13,2,13},{6,2,6,10,5,10},{3,5,3,13,14,13},{2,14,2,14,16,14}});
        add("vein_reward_cache", Kind.CACHE, 0, new double[][]{{0,0,0,16,16,16}});
        add("vein_azure_seal_gate", Kind.GATE, 0, new double[][]{{0,0,5,16,16,11}});
        add("vein_ember_seal_gate", Kind.GATE, 0, new double[][]{{0,0,5,16,16,11}});
        add("vein_origin_seal_gate", Kind.GATE, 0, new double[][]{{0,0,5,16,16,11}});
        add("vein_arena_sensor", Kind.SENSOR, 0, new double[][]{{1,0,1,15,3,15},{4,3,4,12,7,12},{6,7,6,10,11,10}});
        add("vein_crusher", Kind.STATION, 0, new double[][]{{0,0,0,16,16,16}});
        add("vein_washer", Kind.STATION, 0, new double[][]{{0,0,0,16,16,16}});
        add("vein_condenser", Kind.STATION, 0, new double[][]{{0,0,0,16,16,16}});
        add("vein_forge", Kind.STATION, 0, new double[][]{{0,0,0,16,16,16}});
        add("vein_distiller", Kind.STATION, 0, new double[][]{{0,0,0,16,16,16}});
        add("vein_charger", Kind.STATION, 0, new double[][]{{0,0,0,16,16,16}});
        add("vein_ore_cache", Kind.CACHE, 0, new double[][]{{0,0,0,16,16,16}});
        add("vein_reagent_cache", Kind.CACHE, 0, new double[][]{{0,0,0,16,16,16}});
        add("vein_mining_lamp", Kind.LAMP, 0, new double[][]{{3,0,3,13,2,13},{6,2,6,10,5,10},{3,5,3,13,14,13},{2,14,2,14,16,14}});
        add("vein_crystal_beacon", Kind.LAMP, 0, new double[][]{{3,0,3,13,2,13},{6,2,6,10,5,10},{3,5,3,13,14,13},{2,14,2,14,16,14}});
        add("vein_rest_seat", Kind.SEAT, 0, new double[][]{{2,0,2,4,7,4},{12,0,2,14,7,4},{2,0,12,4,7,14},{12,0,12,14,7,14},{1,7,1,15,10,15}});
        add("vein_assay_table", Kind.SENSOR, 0, new double[][]{{1,0,1,15,3,15},{4,3,4,12,7,12},{6,7,6,10,11,10}});
        material("vein_dew_shard", "shard");
        material("vein_dew_concentrate", "concentrate");
        material("vein_frost_shard", "shard");
        material("vein_frost_concentrate", "concentrate");
        material("vein_azure_shard", "shard");
        material("vein_azure_concentrate", "concentrate");
        material("vein_jade_shard", "shard");
        material("vein_jade_concentrate", "concentrate");
        material("vein_ember_shard", "shard");
        material("vein_ember_concentrate", "concentrate");
        material("vein_cinnabar_shard", "shard");
        material("vein_cinnabar_concentrate", "concentrate");
        material("vein_gold_shard", "shard");
        material("vein_gold_concentrate", "concentrate");
        material("vein_violet_shard", "shard");
        material("vein_violet_concentrate", "concentrate");
        material("vein_origin_shard", "shard");
        material("vein_origin_concentrate", "concentrate");
        material("vein_mineral_dust", "dust");
        material("vein_filter_salt", "dust");
        material("vein_binding_resin", "dust");
        material("vein_spirit_coke", "fuel");
        material("vein_blank_key", "key");
        material("vein_azure_key", "key");
        material("vein_ember_key", "key");
        material("vein_origin_key", "key");
        material("vein_spring_tonic", "drink");
        material("vein_ember_tonic", "drink");
        material("vein_azure_tonic", "drink");
    }
    public static final RegistryObject<BlockEntityType<VeinStationBlockEntity>> STATION_ENTITY = ENTITIES.register("vein_station",
            () -> BlockEntityType.Builder.of(VeinStationBlockEntity::new, RESOURCES.values().stream().map(RegistryObject::get)
                    .filter(b -> b instanceof VeinStationBlock).toArray(Block[]::new)).build(null));

    private static void add(String id, Kind kind, int layer, double[][] boxes) {
        var block = BLOCKS.register(id, () -> {
            var p = Block.Properties.of().strength(kind == Kind.ORE ? 3.5F + layer * .25F : 2.5F, 6).sound(SoundType.STONE);
            if (kind == Kind.ORE) p.requiresCorrectToolForDrops();
            return switch (kind) {
                case ROCK, CUBE -> new Block(p);
                case ORE -> new DropExperienceBlock(p, net.minecraft.util.valueproviders.UniformInt.of(1, layer + 1));
                case SLAB -> new SlabBlock(p);
                case LAMP -> new SectLampBlock(p, boxes);
                case SEAT -> new SectSeatBlock(p, boxes, .62);
                case CLUSTER -> new VeinClusterBlock(p.randomTicks(), boxes, layer);
                case STATION, CACHE -> new VeinStationBlock(p, boxes, id, kind == Kind.CACHE);
                case GATE -> new VeinSealBlock(p, boxes, id);
                case SWITCH -> new VeinSwitchBlock(p, boxes);
                case SENSOR -> new VeinSensorBlock(p, boxes, id.endsWith("arena_sensor"));
                case CRAFT -> new VeinCraftingBlock(p, boxes);
                default -> new OrientalDecorationBlock(p, boxes);
            };
        });
        RESOURCES.put(id, block);
        ITEMS.register(id, () -> new BlockItem(block.get(), new Item.Properties()));
    }
    private static void material(String id, String kind) {
        MATERIALS.put(id, ITEMS.register(id, () -> switch (kind) {
            case "fuel" -> new Item(new Item.Properties()) {
                @Override public int getBurnTime(ItemStack stack, RecipeType<?> type) { return 3200; }
            };
            case "drink" -> new VeinTonicItem(id);
            default -> new Item(new Item.Properties());
        }));
    }
    public static BlockState state(String id) { return RESOURCES.get(id).get().defaultBlockState(); }
    public static Item material(String id) { return MATERIALS.get(id).get(); }
    public static Map<String, RegistryObject<Block>> resources() { return Map.copyOf(RESOURCES); }
    public static Map<String, RegistryObject<Item>> materials() { return Map.copyOf(MATERIALS); }
    public static void register(IEventBus bus) {
        BLOCKS.register(bus); ITEMS.register(bus); ENTITIES.register(bus);
        bus.addListener(VeinBlocks::creative);
    }
    private static void creative(BuildCreativeModeTabContentsEvent event) {
        if (event.getTabKey() == CreativeModeTabs.BUILDING_BLOCKS) RESOURCES.values().forEach(b -> event.accept(b.get()));
        if (event.getTabKey() == CreativeModeTabs.INGREDIENTS) MATERIALS.values().forEach(i -> event.accept(i.get()));
        if (event.getTabKey() == CreativeModeTabs.FUNCTIONAL_BLOCKS) RESOURCES.values().forEach(b -> {
            if (b.get() instanceof VeinStationBlock || b.get() instanceof VeinSealBlock || b.get() instanceof VeinSensorBlock
                    || b.get() instanceof SectSeatBlock || b.get() instanceof SectLampBlock || b.get() instanceof VeinSwitchBlock
                    || b.get() instanceof VeinCraftingBlock) event.accept(b.get());
        });
    }
}
